// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/dacharat/wire-gin/database"
	"github.com/dacharat/wire-gin/products"
)

// Injectors from di.go:

func New() products.ProductAPI {
	mongoDatabase := database.NewDatabase()
	productRepository := products.ProvideProductRepository(mongoDatabase)
	productService := products.ProvideProductService(productRepository)
	productAPI := products.ProvideProductAPI(productService)
	return productAPI
}
